function(option_status text value)
    set(status_placeholder_length 24)
    string(RANDOM LENGTH ${status_placeholder_length} ALPHABET " " status_placeholder)
    string(LENGTH "${text}" status_text_length)
    if(status_text_length LESS status_placeholder_length)
        string(SUBSTRING "${text}${status_placeholder}" 0 ${status_placeholder_length} status_text)
    else()
        set(status_text "${text}")
    endif()
    if(${value})
        message(STATUS "${status_text}  : ON")
    else()
        message(STATUS "${status_text}  : OFF")
    endif()
endfunction()

function(string_status text value)
    set(status_placeholder_length 24)
    string(RANDOM LENGTH ${status_placeholder_length} ALPHABET " " status_placeholder)
    string(LENGTH "${text}" status_text_length)
    if(status_text_length LESS status_placeholder_length)
        string(SUBSTRING "${text}${status_placeholder}" 0 ${status_placeholder_length} status_text)
    else()
        set(status_text "${text}")
    endif()
    string(TOLOWER ${value} status_value)
    message(STATUS "${status_text}  : ${value}")
endfunction()

function(lib_status text value)
    set(status_placeholder_length 24)
    string(RANDOM LENGTH ${status_placeholder_length} ALPHABET " " status_placeholder)
    string(LENGTH "${text}" status_text_length)
    if(status_text_length LESS status_placeholder_length)
        string(SUBSTRING "${text}${status_placeholder}" 0 ${status_placeholder_length} status_text)
    else()
        set(status_text "${text}")
    endif()
    message(STATUS "${status_text}  : ${value}")
endfunction()
